services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # Web UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      TZ: Asia/Jakarta
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - demo-login-net

volumes:
  minio-data:

networks:
  demo-login-net:
    external: true
