version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-demo-login
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_login
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - demo-login-net

volumes:
  postgres-data:

networks:
  demo-login-net:
    external: true